### ISSUE TITLE
No fix for digging, mining, etc

### ISSUE THREAD

**Issue by Wad67** [bdew-wurm/timerfix#1]
Probably not added due to some kind of technical limitation, I might have a dig around and see if it can be done.

**Comment by bdew** [comment]
Mining, digging etc are already affected by the action time multiplier. This mod is specifically for things that weren't (usually hardcoded times).

**Comment by Wad67** [comment]
Must be capped in some kind of way, as setting an abnormally high multiplier does not result in instant action times.
